# Development Docker Compose - Database Services Only
# Use this for local development to run just PostgreSQL and Redis
# while running your backend and frontend locally for fast iteration

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: dev-postgres
    restart: unless-stopped
    
    environment:
      - POSTGRES_DB=hierarchical_chat_db
      - POSTGRES_USER=research_user
      - POSTGRES_PASSWORD=research_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/pgdata
    
    ports:
      - "5432:5432"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U research_user -d hierarchical_chat_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis for Session Management & Caching
  redis:
    image: redis:7-alpine
    container_name: dev-redis
    restart: unless-stopped
    
    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru
    
    volumes:
      - redis_dev_data:/data
    
    ports:
      - "6379:6379"
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

# Persistent Volumes
volumes:
  postgres_dev_data:
    driver: local
    name: dev_postgres_data
  
  redis_dev_data:
    driver: local
    name: dev_redis_data
