#!/usr/bin/env python3
"""
Test AI-powered title generation functionality
"""

import requests
import json

API_BASE = "http://localhost:8000/api"

def test_ai_title_generation():
    """Test the new AI title generation endpoint"""
    print("🧪 Testing AI-Powered Title Generation...")
    
    test_questions = [
        "How do I implement a binary search algorithm in Python?",
        "What are the benefits of quantum computing?", 
        "Can you explain machine learning concepts?",
        "Tell me about React hooks and their usage",
        "How to cook perfect pasta?",
        "What is the difference between REST and GraphQL?",
        "Explain blockchain technology in simple terms"
    ]
    
    for i, question in enumerate(test_questions, 1):
        print(f"\n🔍 Test {i}: '{question[:50]}...'")
        
        try:
            # Test the title generation endpoint
            response = requests.post(f"{API_BASE}/generate-title", 
                                   json={"question": question},
                                   timeout=10)
            
            if response.status_code == 200:
                data = response.json()
                generated_title = data.get("title", "No title")
                print(f"✅ Generated Title: '{generated_title}'")
                
                # Validate title quality
                if len(generated_title) > 0 and len(generated_title) <= 50:
                    if generated_title != question[:25] + "...":  # Not just truncated
                        print(f"   ✅ Title appears to be AI-generated (not just truncated)")
                    else:
                        print(f"   ⚠️  Title looks like fallback (might be expected if no API key)")
                else:
                    print(f"   ❌ Invalid title length: {len(generated_title)}")
            else:
                print(f"❌ API Error: {response.status_code}")
                print(f"   Response: {response.text}")
                
        except requests.exceptions.RequestException as e:
            print(f"❌ Request failed: {e}")
        except Exception as e:
            print(f"❌ Unexpected error: {e}")

def test_conversation_with_ai_title():
    """Test that conversations get AI-generated titles on first message"""
    print("\n🧪 Testing Conversation Title Auto-Generation...")
    
    try:
        # Create a new conversation
        create_response = requests.post(f"{API_BASE}/conversations", 
                                      json={"title": "New Chat"})
        
        if create_response.status_code != 200:
            print(f"❌ Failed to create conversation: {create_response.status_code}")
            return
        
        conversation_data = create_response.json()
        conversation_id = conversation_data["node_id"]
        print(f"✅ Created conversation: {conversation_id}")
        
        # Send first message (should trigger AI title generation)
        test_message = "What are the key principles of good software architecture?"
        message_response = requests.post(f"{API_BASE}/conversations/{conversation_id}/messages",
                                       json={"message": test_message})
        
        if message_response.status_code == 200:
            message_data = message_response.json()
            conversation_title = message_data.get("conversation_title")
            
            print(f"✅ First message sent: '{test_message[:40]}...'")
            print(f"✅ AI-Generated Title: '{conversation_title}'")
            
            # Validate that title was actually generated by AI
            if conversation_title and conversation_title != "New Chat":
                print("   ✅ Title was successfully generated and updated!")
            else:
                print("   ⚠️  Title was not generated (might be expected if no API key)")
        else:
            print(f"❌ Failed to send message: {message_response.status_code}")
            print(f"   Response: {message_response.text}")
            
    except Exception as e:
        print(f"❌ Test failed: {e}")

if __name__ == "__main__":
    print("🚀 Starting AI Title Generation Tests...")
    print("Make sure the backend server is running on http://localhost:8000")
    print("=" * 60)
    
    test_ai_title_generation()
    test_conversation_with_ai_title()
    
    print("\n" + "=" * 60)
    print("🎉 AI Title Generation Tests Complete!")
    print("\n📋 Summary:")
    print("   • All titles should now be generated by AI (Groq API)")
    print("   • Fallback to word extraction only if API fails")
    print("   • Both main conversations and subchats use AI titles")